name: Build and Deploy
on:
  push:
    branches:
      - Nov20_Jeff  # Replace with your default branch if it's not 'main'
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '21.6.1'  # Set the Node.js version according to your project requirements
    - name: List
      run: ls

    - name: Install Dependencies
      run: npm install
      working-directory: ./app

    - name: Build
      run: npm run build
      working-directory: ./app

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        BRANCH: gh-pages  # The branch to deploy to
        FOLDER: app  # The folder the action should deploy
        CLEAN: true  # Automatically remove deleted files from the deployment
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
